version: '3.9'

services:
  postgres:
    image: postgres:18
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: IAM
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:    
      - ./init-db:/docker-entrypoint-initdb.d 

  authapi:
    container_name: authapi
    build:
      context: .
      dockerfile: ./Auth.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Jwt__Issuer: auth.api
      Jwt__Audience: AllMicroservices
      Jwt__Key: Dz65RkF0o2n023iLknkltZYz4XAMelP+mVY4le60kbY=
      Jwt__LifetimeMinutes: 15
      ConnectionStrings__DefaultConnection: "Host=postgresdb;Port=5432;Database=IAM;Username=postgres;Password=0000"
    ports:
      - "5002:8080"
    depends_on:
      - postgres
    networks:
      - backend

  userapi:
    build:
      context: .
      dockerfile: ./User.API/Dockerfile
    container_name: userapi
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgresdb;Port=5432;Database=IAM;Username=postgres;Password=0000
      Services__AuthService: http://authservice:8080
      Jwt__Issuer: authapi
      Jwt__Audience: AllMicroservices
      Jwt__Key: Dz65RkF0o2n023iLknkltZYz4XAMelP+mVY4le60kbY=
    depends_on:
      - postgres
      - authapi
    ports:
      - "5001:8080"
    networks:
      - backend

  erpapi:
    build:
      context: .
      dockerfile: ./ERP/Dockerfile
    container_name: erpapi
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DbConnectionString: Host=postgresdb;Port=5432;Database=ERP;Username=postgres;Password=0000
      Jwt__Issuer: authapi
      Jwt__Audience: AllMicroservices
      Jwt__Key: Dz65RkF0o2n023iLknkltZYz4XAMelP+mVY4le60kbY=
    depends_on:
      - postgres
      - authapi
    ports:
      - "5003:8080"
    networks:
      - backend


  aiservice:
    build:
      context: .
      dockerfile: ./AIService/Dockerfile # Vérifie bien le chemin vers ton Dockerfile
    container_name: aiservice
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Gemini__ApiKey: "TON_API_KEY_ICI" # Optionnel : tu peux passer la clé ici
    ports:
      - "5091:8080"
    networks:
      - backend


  apigateway:
    build: 
      context: .
      dockerfile: ./Gateway/Dockerfile
    container_name: apigateway
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ReverseProxy__Clusters__authCluster__Destinations__d1__Address: http://authapi:8080/
      ReverseProxy__Clusters__usersCluster__Destinations__d1__Address: http://userapi:8080/
      ReverseProxy__Clusters__erpCluster__Destinations__d1__Address: http://erpapi:8080/ 
      ReverseProxy__Clusters__aiCluster__Destinations__d1__Address: http://aiservice:8080/
    ports:
      - "5000:8080"
    depends_on:
      - authapi
      - userapi
      - erpapi 
      - aiservice
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: